### ISSUE TITLE
Startup Request not working

### ISSUE THREAD

**Issue by Phil061995** [DrFreas/VCH#16]
**Describe the bug**
When I try to set a Startup Request, it shows up for a second and disappers thereafter. This also happens if no further groundstate or clearance received flag is set. All other requests are working as expected. So it is currently not possible to use the Startup Request.

**To Reproduce**
1. set Startup Request

**Desktop (please complete the following information):**
 - latest VCH and Euroscope Beta
 - Ground Radar Plugin in use

**Comment by DrFreas** [comment]
Noticed that behaviour as well, haven't figured out what caused it yet.

**Comment by DrFreas** [comment]
This should be fixed now in v0.8.1.
