### ISSUE TITLE
TagItem "Startup" and "Pushback"

### ISSUE THREAD

**Issue by Phil061995** [DrFreas/VCH#17]
**Is your feature request related to a problem? Please describe.**
As we at Frankfurt are now working with the updated Groundradar Plugin, especially Delivery need to focus on the use of different lists. To enable an efficient workflow it would be a great help if we could have a TagItem to set up the ES Groundstate "Start-Up" and "Push" with a single click on an item (e.g. at an item at the start-up list). So Delivery don't need to select the states via the ground states lists. 

Thanks!

**Comment by DrFreas** [comment]
Can be done quite easily, will consider for next release. Would be action only (to set up as a button press), a TagItem would be possible as well.

**Comment by DrFreas** [comment]
Unfortunatly it is not that easy as I found out. This will be postponed for now since Euroscope apparently doesn't allow to change ground states that easily.
