### ISSUE TITLE
Potential mix of lists using EuroScope's FlightPlan functionality

### ISSUE THREAD

**Issue by nikki2048** [DrFreas/VCH#18]
Since the new ground status items are now shared between controllers, what happens if multiple controllers are utilizing the plugin simultaneously? Since these lists are shared and the plugin has no way of telling whether an A/C is actively controlled and by what controller (caused by the lack of tag-tracking), are request lists merged together? 

Take the following example:
I am controlling C_GND
Some other controller is controlling W_GND
The tag-information (FlightPlan / Remarks) are shared between controllers. If I assign a specific status to an aircraft, the other controller will receive this information too - since the data is shared. Does that mean, that this aircraft would also take a certain position in the request list of the controller manning W_GND, or are these lists still separated. If I understood the functionality correctly, the lists are then concatenated and thus the other controller has info on an aircraft that he/she is not controlling hence making the list almost unusable (in my opinion) as I can't tell who is actively being controlled by myself and subsequently the request-list that I had set up for my sector. There's no point for me to see this information for a different station, since the list is purely internal. 

If the above is the case, then that could cause confusion between controllers and hindering them, rather than helping. Perhaps, for handover to a different controller, the current request-data could be stored somewhere and then pulled back down by the next controller. 
E.g.:
1. C_GND loggs off, but types `.vch save`
2. The new controller, taking over C_GND, loggs in and enters `.vch load`
3. The previously stored data (request orders, etc.) are saved and then transferred to the new controller making the handover as seamless as possible.

As I stated, I'm not sure whether I understood the functionality of the programm correctly, however this is a concern that came to my mind today, when listening to the presentation.

**Comment by DrFreas** [comment]
Hi,
yes I am aware of this potential issue. I don't know how much of an issue it is since everybody knows exactly who he (or she) is talking to, right? :) We will see how it works out, I don't think this should be a big issue.
