### ISSUE TITLE
Request Timer

### ISSUE THREAD

**Issue by BrooksEU** [DrFreas/VCH#2]
Having a new item type that can be set next to the „req“ called T. Showing the Time that has passed in minutes since the Request Flag has been set for better overall priority finding and Situational awareness on the ground. Number gets red after 5 min for RxC, 4 mins for RxP, 3 mins for RxT

**Comment by DrFreas** [comment]
Maybe if it even wasn't an extra tag item, but already included in the tag itself. I am doing some redesigning of the code atm which includes complete "syncability", so I will definetly have a look into this.

**Comment by DrFreas** [comment]
This will be included in the next update.

**Comment by DrFreas** [comment]
This is now included in v0.4.4 as an extra tag item.
