### ISSUE TITLE
Request to replace "R1C" by "C1"

### ISSUE THREAD

**Issue by Phil061995** [DrFreas/VCH#20]
Would it be possible to replace the request text "R1C, R1P" etc, by "C1, P1, T1", etc. It's obvious that it is a request, as the "pending request" TagItem is used, and most of the time at a request column at a list. So without the R for request and with C, P at the beginning, sorting by request would be much better at Euroscope. :)

**Comment by DrFreas** [comment]
Makes sense, will include an option for that in the next version.
