### ISSUE TITLE
VCH 0.8.2 error

### ISSUE THREAD

**Issue by DevonFly** [DrFreas/VCH#21]
**Describe the bug**
Hello. I downloaded the source code plus the VCH.dll for 0.8.2, but when I load it into Euroscope, I get a meesage saying it is 0.8.1, even though the downloaded .dll is the only one in the folder. I have downloaded it twice and I get the same error (By the way, this is a really useful plugin).

**To Reproduce**
1. Go to '...' VCH download button & download source code zip file and .dll to a folder VCH-0.8.2
2. Extract Zip file
3. Open Euroscope & load VCH in plugin option

**Expected behavior**
It should show the file as 0.8.2
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 
![VCH 0 8 2 error](https://user-images.githubusercontent.com/53476922/186746812-91767f87-0c21-41ff-836e-237843ca52f6.jpg)
![VCH 0 8 2 error 2](https://user-images.githubusercontent.com/53476922/186747252-cc6aec2e-c19d-4ad5-bd85-a6f6f57ae877.jpg)

**Comment by DrFreas** [comment]
Hi,
thank you for your feedback. I obviousl forgot to change the version number in the plugin itself, uploading a fix in a few minutes.

**Comment by DevonFly** [comment]
Great ! Thanks

Robin Meads
07909-540320

**Comment by DrFreas** [comment]
Sorry for the inconvenience. It is fixed now (might take a few more minutes until the online source for version checking is updated so it might protest that there is a new version. Newest is now v0.8.2hf).

Thank you!
