### ISSUE TITLE
Issue with the reminder feature

### ISSUE THREAD

**Issue by goulven04** [DrFreas/VCH#24]
**Describe the bug**:
* In all cases, nothing is displayed under the tag item "VCH / Reminder" in the list
* If I click on the tag item (mapped to "VCH / Switch Reminder"), I can see the string "REM" in the flight strip annotations, but nothing in the list
* If I click again on the tag item, the "REM" does NOT disappear from the flight strip annotations, and nothing still appear in the list

**Desktop (please complete the following information)**:
* Windows 11
* Euroscope 3.2.a(r34)
* VCH 0.8.2hf

**Additional context**:
* I use the default colors and default characters for reminderon and reminderoff
* All the other features of VCH works perfectly

Please let me know if there is anything I can do on my side to further troubleshoot.
Thank you.

**Comment by DrFreas** [comment]
Hi,
thank you for your report. Apparently something changed with the flight strip annotations or with a plugin that might be interfering with that. Could you send me a list of all plugins you currently use?
I was indeed able to reproduce this.

**Comment by goulven04** [comment]
Hi,
Thank you. Here is my list of plugins:
<img width="566" alt="euroscope_plugins" src="https://user-images.githubusercontent.com/95419932/202906131-5490a324-87d2-4c7c-a245-c0fdc36cc91f.png">

**Comment by goulven04** [comment]
I have noticed a few things:
* `.vch reminder off .` makes the `.` appear in the list.
* if `vch_nrm` is set in the configuration file, then `.` appears straight away after loading Euroscope

I'm no C++ expert, but It is then possible that the default characters are not properly loaded because of the way the string comparison is done. That also would explain why the REM string can be set in the flight strip, but cannot be removed, as `hasReminder()` always return `false`.

I've submitted #25, unfortunately I don't have Visual Studio available to validate it.

**Comment by DrFreas** [comment]
The way this works is that it doesn't (or shouldn't) matter what the characters are set to, "REM" is the only thing that is stored and also read out. It has worked in the past, so I'm not sure what exactly broke it, I will have a look into this, maybe with some never VS-version it just doesn't work anymore without strcmp or something else has gone wrong. I might need a few days to get the time to look into this.
Thank you again for reporting this, this will absolutely be fixed.

**Comment by goulven04** [comment]
I finally was able to setup Visual Studio and compiled the DL. I confirm that the changes fix the bug. I also found another bug where "Reminder only when active" is not selectable because of duplicated Tag Item ID and added a commit to that same PR.
