### ISSUE TITLE
VCH causing flight plan storms on VATSIM

### ISSUE THREAD

**Issue by mikeyusc** [DrFreas/VCH#26]
**Describe the bug**
Currently after a controller issues a /VCH/REQ packet to be sent, other controllers & the same controller seem to issue up to thousands of Amendments, causing a storm that can freeze all ES clients within range.

We've observed multiple storms like this today alone, and this needs to be addressed ASAP or the plugin risks being banned from the network.

**Comment by DrFreas** [comment]
This should for now be fixed with version 0.8.3
