### ISSUE TITLE
Departure Queue

### ISSUE THREAD

**Issue by KozziOS** [DrFreas/VCH#3]
When it is busy there can be multiple aircraft waiting at various holding points at the runway waiting for departure. Is it possible you can have a request queue for departures which clears when the ground status is set to DEPA?

**Comment by DrFreas** [comment]
Hi, thanks for your idea. That could be done very easy indeed. I shall inclue this in the next update which is almost finished and just requires some more testing, so stay tuned!

**Comment by DrFreas** [comment]
This will be included in the next update.

**Comment by DrFreas** [comment]
This is now included in v0.4.4.
